server:
  port: 9000
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB

spring:
  application:
    name: bingo-authentication-server
  data:
    mongodb:
      database: bingo
      uri: mongodb://localhost:27017/bingo?retryWrites=true&w=majority

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}